### PR TITLE
Show the restore output to the user.

### LINKED ISSUE #39: Restore database from file generates js function error
Error occurred, WARNING: failed to find js function function "xt.js_init" does not exist. could not find js_init.js.

### PR DESCRIPTION
**Pull request by elipup**
As per a discussion with @bixwilson, this will give the output of a database restore in an info box. This way, the user can see if the errors can be ignored or not.
I think this resolves #39 since the underlying problem is not with xTau.

### CODE REVIEW

File: database.sh [hunk 1]
```diff
@@ -340,10 +340,11 @@ restore_database() {
         return $RET
     else
         log "Restoring database $DATABASE from file $1 on server $PGHOST:$POSTPORT"
-        log_exec pg_restore --username "$PGUSER" --port "$POSTPORT" --host "$PGHOST" --dbname "$DATABASE" "$1"
+        pg_restore --username "$PGUSER" --port "$POSTPORT" --host "$PGHOST" --dbname "$DATABASE" "$1" 2>restore_output.log
```
Comment (gilmoskowitz) [inline database.sh]: This relative path raises some general questions throughout xTAU
- what is the current working directory?
- what if the user doesn't have permission to write in the CWD?
- do we want to save these output files after successful runs?
- do we want to overwrite these files during successful or unsuccessful runs?

Comment (elipup) [inline database.sh]: The working directory is wherever the utility is run, which should be changed to be static.
Right now, we run the utility from the cloned repository, and therefore the working directory will be writeable else the clone would have failed.
The output files are saved in the logs. They are not overwritten.
