### PR TITLE
misc bug fixes

### LINKED ISSUE #127: Can't install on ubunto16.04
when I execute ./xtuple-utility.sh -a, occurs error:
make: Leaving directory '/opt/xtuple/4.10.1/xtuple-web/xtuple/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm WARN engine escodegen@1.9.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine request@2.83.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine request-promise-native@1.0.5: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'parse5'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.10.0-28-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /opt/xtuple/4.10.1/xtuple-web/xtuple
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

...

11:26:46 xtuple >> Creating systemd service unit using filename /etc/systemd/system/xtuple-xtuple-web.service

/etc/xtuple/4.10.1/xtuple-web/config.js:30
      port: ,
            ^
<<ERROR 2017-12-26T03:26:46.343Z>> Unrecoverable exception. Unexpected token ,SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at exports.build (/opt/xtuple/4.10.1/xtuple-web/xtuple/scripts/lib/build_all.js:123:16)
    at /opt/xtuple/4.10.1/xtuple-web/xtuple/scripts/build_app.js:35:3
    at Object.<anonymous> (/opt/xtuple/4.10.1/xtuple-web/xtuple/scripts/build_app.js:55:2)
    at Module._compile (module.js:456:26)
11:26:46 xtuple >> All set! You should now be able to log on to this server at https://172.16.16.41: with username admin and password admin. Make sure you change your password!

### LINKED ISSUE #128: Multiple issues trying to install via the "full installation" switch
I run into the following when running the `xtuple-utility.sh` script:

```
22:28:27 xtuple >> Creating upstart script using filename /etc/init/xtuple-xtuple-web.conf

/etc/xtuple/4.11.1/xtuple-web/config.js:30
      port: ,
            ^
<<ERROR 2018-01-02T22:28:27.554Z>> Unrecoverable exception. Unexpected token ,SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at exports.build (/opt/xtuple/4.11.1/xtuple-web/xtuple/scripts/lib/build_all.js:123:16)
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/scripts/build_app.js:35:3
    at Object.<anonymous> (/opt/xtuple/4.11.1/xtuple-web/xtuple/scripts/build_app.js:55:2)
    at Module._compile (module.js:456:26)
xtuple-xtuple-web: unrecognized service
```

If I fix the config file, by filling out the empty port locations my own ports I then run into an issue running it:

```
<<ERROR 2018-01-02T22:37:05.821Z>> Database Error! function xt.refresh_share_user_cache() does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.823Z>> Database Error! Last query was: select xt.refresh_share_user_cache()
<<ERROR 2018-01-02T22:37:05.824Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.827Z>> Database Error! function xt.post(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.828Z>> Database Error! Last query was: select xt.post($${"nameSpace":"XT","type":"Session","dispatch":{"functionName":"schema","parameters":"xm"},"username":"admin"}$$) as request
<<ERROR 2018-01-02T22:37:05.828Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.836Z>> Database Error! function xt.post(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.837Z>> Database Error! Last query was: select xt.post($${"nameSpace":"XT","type":"Session","dispatch":{"functionName":"schema","parameters":"sys"},"username":"admin"}$$) as request
<<ERROR 2018-01-02T22:37:05.838Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.841Z>> Database Error! function xt.get(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.842Z>> Database Error! Last query was: select xt.get($${"nameSpace":"SYS","type":"SessionStore","username":"node"}$$) as request
<<ERROR 2018-01-02T22:37:05.843Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.847Z>> Database Error! function xt.post(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.848Z>> Database Error! Last query was: select xt.post($${"nameSpace":"XT","type":"Session","dispatch":{"functionName":"privileges","parameters":null},"username":"admin"}$$) as request
<<ERROR 2018-01-02T22:37:05.848Z>> Database Error! DB name = 4111
schema error { '0':
   { code: 'xt1001',
     params: { error: [Object] },
     messageKey: '_datasourceError',
     message: [Function] } }
schema error { '0':
   { code: 'xt1001',
     params: { error: [Object] },
     messageKey: '_datasourceError',
     message: [Function] } }
<<LOG 2018-01-02T22:37:05.856Z>> Share Users Cache warming errors:{ [error: function xt.refresh_share_user_cache() does not exist]
  length: 221,
  name: 'error',
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'parse_func.c',
  line: '523',
  routine: 'ParseFuncOrColumn' }
Trace: Share Users Cache warming errors:
    at cacheShareUsersWarmed (/opt/xtuple/4.11.1/xtuple-web/xtuple/node-datasource/main.js:194:15)
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/node-datasource/lib/ext/datasource.js:282:15
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:278:11
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/lib/pool.js:38:18
    at null.<anonymous> (/opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/lib/client.js:137:7)
    at g (events.js:180:16)
    at emit (events.js:117:20)
    at Socket.<anonymous> (/opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/lib/connection.js:87:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
```

### PR DESCRIPTION
**Pull request by gilmoskowitz**
Merge after #130 

- fixes #128 
- fixes #127

### CODE REVIEW

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
jenkins - retest this please
( looks like jenkins wasn't actually merging in the pr! )

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

File: config.sh [hunk 1]
```diff
@@ -28,7 +28,7 @@ NGINX_SITE=
 # auto populated if site exists, otherwise can be used to create a site
 NGINX_DOMAIN=
 NGINX_HOSTNAME=
-NGINX_PORT=
+NGINX_PORT=${NGINX_PORT:-8443}
```
Comment (xtpclark) [inline config.sh]: This was set because config.js requires it. The process flow for nginx setup needs some review.  Node.js - config.js needs to be streamlined and generally improved.
